#! /bin/bash
# Print the time, truncated down 30 mintues, minus 30 minutes

time=$(echo "$(date "+%Y%m%d%H%M") - ($(date +%M)%30)" | bc)
stime=$(printf '%d\n' "$time")
y=${stime:0:4}
m=${stime:4:2}
d=${stime:6:2}
H=${stime:8:2}
M=${stime:10:2}
echo "$m/$d/$y,$H:$M,"
